### ISSUE TITLE
Extend API to build transactions for Hydra

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/tx-village#92]
## Subtasks
- [ ] set ex budget to maximum for all transactions (no Ogmios evaluation needed)
- [ ] set tx fee to 0 for all transactions
- [ ] implement HydraClient with ChainQuery and Submitter trait
  - [ ] queryUtxos will parse the whole snapshot (suboptimal, but good enough for the first iteration)
  - [ ] evaluateTx always returns error (should not be used)
  - [ ] read protocolParameters from a file

**Comment by JTorfs** [comment]
Hey @szg251 Does any of the tasks relating to the Hydra case include the deployment of the protocol and the head? Similar to the nixos thing we have now?
